export const models = [
  { path: "./models/mystical_forest_cartoon.glb", scale: 0.01, position: [0, 0, 0], rotation: [0, 0, 0], name: 'Mystical Forest' },
  { path: "./models/my_avatar.glb", scale: 2, position: [-3, 2, 50], rotation: [0, Math.PI, 0], isAvatar: true, name: 'Avatar' },
  { path: "./models/Charzard Flying.glb", scale: 3, position: [0, 20, 0], rotation: [0, 0, 0], isCharizard: true, name: 'Charizard' },
  { path: "./models/phantump_shiny.glb", scale: 0.01, position: [3, 5, 9], rotation: [0, 0, 0], name: 'Phantump' },
  { path: "./models/salamence.glb", scale: 0.3, position: [-30, 16, 27], rotation: [0, (Math.PI * 2) / 3, 0], name: 'Salamence' },
  { path: "./models/bulbasaur.glb", scale: 2, position: [13, -0.5, 22], rotation: [0, 0, 0], name: 'Bulbasaur' },
  { path: "./models/lucario_and_riolu_toy_edition.glb", scale: 2, position: [-27, 6.5, 6], rotation: [0, Math.PI / 3, 0], name: 'Lucario' },
  { path: "./models/eevee.glb", scale: 3.5, position: [7, 0, 10], rotation: [0, 0, 0], name: 'Eevee' },
  { path: "./models/pikachu.glb", scale: 0.03, position: [5, 0, 10], rotation: [0, 0, 0], name: 'Pikachu' },
  { path: "./models/umbreon.glb", scale: 3, position: [6, 0, 10], rotation: [0, 0, 0], name: 'Umbreon' },
  { path: "./models/pidgey.glb", scale: 0.4, position: [-2.5, 7, 32], rotation: [0, Math.PI, 0], name: 'Pidgey' },
  { path: "./models/arcanine.glb", scale: 1, position: [10, 3.2, 29], rotation: [0, (-Math.PI * 3) / 4, 0], name: 'Arcanine' },
  { path: "./models/ssbb_pokemon_trainer.glb", scale: 0.4, position: [-14, 3, 21], rotation: [0, Math.PI / 2, 0], isTrainer: true, name: 'Trainer' },
  { path: "./models/plakia.glb", scale: 0.6, position: [-32, 23, -19], rotation: [0, Math.PI / 2, 0], name: 'Plakia' },
  { path: "./models/entei.glb", scale: 0.4, position: [-25, 15.5, -4], rotation: [0, Math.PI / 2, 0], name: 'Entei' },
  { path: "./models/reshiram.glb", scale: 3.5, position: [60, 23, -14], rotation: [0, -Math.PI / 4, 0], name: 'Reshiram' },
  { path: "./models/old_medieval_sign_board.glb", scale: 7, position: [3, 0, 44], rotation: [0, 0, 0], isSignboard: true, name: 'Signboard' },
];
